[package]
name = "narrowway-crypt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
narrowway = { git = "https://github.com/31core/NarrowWay.git" }
rand = "0.8.5"
