[package]
name = "narrowway-crypt"
version = "0.1.5"
edition = "2021"

[dependencies]
blake2 = "0.10.6"
clap = { version = "4.5.16", features = ["derive"] }
narrowway = { git = "https://github.com/31core/NarrowWay.git" }
rand = "0.8.5"
